"use client";

import { useEffect, useState } from "react";

interface AbstractBrainSilhouetteProps {
  className?: string;
}

export default function AbstractBrainSilhouette({
  className = "",
}: AbstractBrainSilhouetteProps) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    return (
      <div
        className={`absolute inset-0 pointer-events-none ${className}`}
        style={{ zIndex: -1 }}
      />
    );
  }

  return (
    <div
      className={`absolute inset-0 pointer-events-none ${className}`}
      style={{ zIndex: -1 }}
    >
      <svg
        viewBox="0 0 1200 800"
        className="w-full h-full opacity-80"
        style={{ filter: "blur(0.2px)" }}
      >
        <defs>
          <linearGradient
            id="brainGradient"
            x1="0%"
            y1="0%"
            x2="100%"
            y2="100%"
          >
            <stop offset="0%" stopColor="#88B772" stopOpacity="0.8" />
            <stop offset="50%" stopColor="#88B772" stopOpacity="0.4" />
            <stop offset="100%" stopColor="#88B772" stopOpacity="0.1" />
          </linearGradient>
          <linearGradient
            id="signalGradient"
            x1="0%"
            y1="0%"
            x2="100%"
            y2="100%"
          >
            <stop offset="0%" stopColor="#88B772" stopOpacity="0" />
            <stop offset="30%" stopColor="#88B772" stopOpacity="0.6" />
            <stop offset="70%" stopColor="#88B772" stopOpacity="0.8" />
            <stop offset="100%" stopColor="#88B772" stopOpacity="0" />
          </linearGradient>
        </defs>

        {/* Minimalist Brain Network - Anatomically accurate node placement */}

        {/* Left Hemisphere - Frontal Lobe (Top Front) */}
        <circle
          cx="250"
          cy="180"
          r="2.2"
          fill="#88B772"
          opacity="0.7"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.4;0.8;0.4"
            dur="3.2s"
            repeatCount="indefinite"
          />
          <animate
            attributeName="r"
            values="1.7;2.7;1.7"
            dur="3.2s"
            repeatCount="indefinite"
          />
        </circle>
        <circle
          cx="220"
          cy="200"
          r="1.8"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="2.8s"
            repeatCount="indefinite"
            begin="0.5s"
          />
          <animate
            attributeName="r"
            values="1.3;2.3;1.3"
            dur="2.8s"
            repeatCount="indefinite"
            begin="0.5s"
          />
        </circle>
        <circle
          cx="200"
          cy="230"
          r="2.0"
          fill="#88B772"
          opacity="0.65"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.75;0.35"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1s"
          />
          <animate
            attributeName="r"
            values="1.5;2.5;1.5"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1s"
          />
        </circle>

        {/* Left Hemisphere - Parietal Lobe (Top Back) */}
        <circle
          cx="280"
          cy="220"
          r="1.9"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="3.1s"
            repeatCount="indefinite"
            begin="0.3s"
          />
          <animate
            attributeName="r"
            values="1.4;2.4;1.4"
            dur="3.1s"
            repeatCount="indefinite"
            begin="0.3s"
          />
        </circle>
        <circle
          cx="300"
          cy="250"
          r="2.1"
          fill="#88B772"
          opacity="0.7"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.4;0.8;0.4"
            dur="2.9s"
            repeatCount="indefinite"
            begin="0.7s"
          />
          <animate
            attributeName="r"
            values="1.6;2.6;1.6"
            dur="2.9s"
            repeatCount="indefinite"
            begin="0.7s"
          />
        </circle>
        <circle
          cx="270"
          cy="280"
          r="1.7"
          fill="#88B772"
          opacity="0.55"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.65;0.25"
            dur="3.4s"
            repeatCount="indefinite"
            begin="1.2s"
          />
          <animate
            attributeName="r"
            values="1.2;2.2;1.2"
            dur="3.4s"
            repeatCount="indefinite"
            begin="1.2s"
          />
        </circle>

        {/* Left Hemisphere - Temporal Lobe (Side) */}
        <circle
          cx="180"
          cy="320"
          r="1.8"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="3.6s"
            repeatCount="indefinite"
            begin="1.8s"
          />
          <animate
            attributeName="r"
            values="1.3;2.3;1.3"
            dur="3.6s"
            repeatCount="indefinite"
            begin="1.8s"
          />
        </circle>
        <circle
          cx="200"
          cy="350"
          r="2.0"
          fill="#88B772"
          opacity="0.65"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.75;0.35"
            dur="3.3s"
            repeatCount="indefinite"
            begin="0.4s"
          />
          <animate
            attributeName="r"
            values="1.5;2.5;1.5"
            dur="3.3s"
            repeatCount="indefinite"
            begin="0.4s"
          />
        </circle>
        <circle
          cx="160"
          cy="380"
          r="1.6"
          fill="#88B772"
          opacity="0.55"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.65;0.25"
            dur="2.5s"
            repeatCount="indefinite"
            begin="1.1s"
          />
          <animate
            attributeName="r"
            values="1.1;2.1;1.1"
            dur="2.5s"
            repeatCount="indefinite"
            begin="1.1s"
          />
        </circle>

        {/* Left Hemisphere - Occipital Lobe (Back) */}
        <circle
          cx="320"
          cy="380"
          r="1.9"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.6s"
          />
          <animate
            attributeName="r"
            values="1.4;2.4;1.4"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.6s"
          />
        </circle>
        <circle
          cx="290"
          cy="410"
          r="2.2"
          fill="#88B772"
          opacity="0.65"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.75;0.35"
            dur="2.8s"
            repeatCount="indefinite"
            begin="1.3s"
          />
          <animate
            attributeName="r"
            values="1.7;2.7;1.7"
            dur="2.8s"
            repeatCount="indefinite"
            begin="1.3s"
          />
        </circle>

        {/* Center - Corpus Callosum (Removed to keep text area clean) */}

        {/* Right Hemisphere - Frontal Lobe (Top Front) */}
        <circle
          cx="950"
          cy="180"
          r="2.2"
          fill="#88B772"
          opacity="0.7"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.4;0.8;0.4"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.2s"
          />
          <animate
            attributeName="r"
            values="1.7;2.7;1.7"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.2s"
          />
        </circle>
        <circle
          cx="980"
          cy="200"
          r="1.8"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="2.8s"
            repeatCount="indefinite"
            begin="0.7s"
          />
          <animate
            attributeName="r"
            values="1.3;2.3;1.3"
            dur="2.8s"
            repeatCount="indefinite"
            begin="0.7s"
          />
        </circle>
        <circle
          cx="1000"
          cy="230"
          r="2.0"
          fill="#88B772"
          opacity="0.65"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.75;0.35"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1.2s"
          />
          <animate
            attributeName="r"
            values="1.5;2.5;1.5"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1.2s"
          />
        </circle>

        {/* Right Hemisphere - Parietal Lobe (Top Back) */}
        <circle
          cx="920"
          cy="220"
          r="1.9"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="3.1s"
            repeatCount="indefinite"
            begin="0.9s"
          />
          <animate
            attributeName="r"
            values="1.4;2.4;1.4"
            dur="3.1s"
            repeatCount="indefinite"
            begin="0.9s"
          />
        </circle>
        <circle
          cx="900"
          cy="250"
          r="2.1"
          fill="#88B772"
          opacity="0.7"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.4;0.8;0.4"
            dur="2.9s"
            repeatCount="indefinite"
            begin="0.3s"
          />
          <animate
            attributeName="r"
            values="1.6;2.6;1.6"
            dur="2.9s"
            repeatCount="indefinite"
            begin="0.3s"
          />
        </circle>
        <circle
          cx="930"
          cy="280"
          r="1.7"
          fill="#88B772"
          opacity="0.55"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.65;0.25"
            dur="3.4s"
            repeatCount="indefinite"
            begin="1.6s"
          />
          <animate
            attributeName="r"
            values="1.2;2.2;1.2"
            dur="3.4s"
            repeatCount="indefinite"
            begin="1.6s"
          />
        </circle>

        {/* Right Hemisphere - Temporal Lobe (Side) */}
        <circle
          cx="1020"
          cy="320"
          r="1.8"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="3.6s"
            repeatCount="indefinite"
            begin="0.8s"
          />
          <animate
            attributeName="r"
            values="1.3;2.3;1.3"
            dur="3.6s"
            repeatCount="indefinite"
            begin="0.8s"
          />
        </circle>
        <circle
          cx="1000"
          cy="350"
          r="2.0"
          fill="#88B772"
          opacity="0.65"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.75;0.35"
            dur="3.3s"
            repeatCount="indefinite"
            begin="1.4s"
          />
          <animate
            attributeName="r"
            values="1.5;2.5;1.5"
            dur="3.3s"
            repeatCount="indefinite"
            begin="1.4s"
          />
        </circle>
        <circle
          cx="1040"
          cy="380"
          r="1.6"
          fill="#88B772"
          opacity="0.55"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.65;0.25"
            dur="2.5s"
            repeatCount="indefinite"
            begin="0.5s"
          />
          <animate
            attributeName="r"
            values="1.1;2.1;1.1"
            dur="2.5s"
            repeatCount="indefinite"
            begin="0.5s"
          />
        </circle>

        {/* Right Hemisphere - Occipital Lobe (Back) */}
        <circle
          cx="880"
          cy="380"
          r="1.9"
          fill="#88B772"
          opacity="0.6"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.7;0.3"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.8s"
          />
          <animate
            attributeName="r"
            values="1.4;2.4;1.4"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.8s"
          />
        </circle>
        <circle
          cx="910"
          cy="410"
          r="2.2"
          fill="#88B772"
          opacity="0.65"
          className="node-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.75;0.35"
            dur="2.8s"
            repeatCount="indefinite"
            begin="1.5s"
          />
          <animate
            attributeName="r"
            values="1.7;2.7;1.7"
            dur="2.8s"
            repeatCount="indefinite"
            begin="1.5s"
          />
        </circle>

        {/* Brainstem (Removed to clean up bottom area) */}

        {/* Minimalist Neural Connections - Anatomically accurate */}
        {/* Left Hemisphere - Frontal to Parietal */}
        <line
          x1="250"
          y1="180"
          x2="220"
          y2="200"
          stroke="#88B772"
          strokeWidth="1.3"
          opacity="0.5"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.6;0.3"
            dur="3.2s"
            repeatCount="indefinite"
          />
        </line>
        <line
          x1="220"
          y1="200"
          x2="200"
          y2="230"
          stroke="#88B772"
          strokeWidth="1.2"
          opacity="0.45"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.55;0.25"
            dur="2.8s"
            repeatCount="indefinite"
            begin="0.5s"
          />
        </line>
        <line
          x1="280"
          y1="220"
          x2="300"
          y2="250"
          stroke="#88B772"
          strokeWidth="1.4"
          opacity="0.55"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.65;0.35"
            dur="3.1s"
            repeatCount="indefinite"
            begin="0.3s"
          />
        </line>
        <line
          x1="300"
          y1="250"
          x2="270"
          y2="280"
          stroke="#88B772"
          strokeWidth="1.1"
          opacity="0.4"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.2;0.5;0.2"
            dur="2.9s"
            repeatCount="indefinite"
            begin="0.7s"
          />
        </line>

        {/* Left Hemisphere - Frontal to Temporal */}
        <line
          x1="200"
          y1="230"
          x2="180"
          y2="320"
          stroke="#88B772"
          strokeWidth="1.0"
          opacity="0.35"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.15;0.45;0.15"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1s"
          />
        </line>
        <line
          x1="180"
          y1="320"
          x2="200"
          y2="350"
          stroke="#88B772"
          strokeWidth="1.3"
          opacity="0.5"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.6;0.3"
            dur="3.6s"
            repeatCount="indefinite"
            begin="1.8s"
          />
        </line>
        <line
          x1="200"
          y1="350"
          x2="160"
          y2="380"
          stroke="#88B772"
          strokeWidth="1.1"
          opacity="0.4"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.2;0.5;0.2"
            dur="3.3s"
            repeatCount="indefinite"
            begin="0.4s"
          />
        </line>

        {/* Left Hemisphere - Parietal to Occipital */}
        <line
          x1="270"
          y1="280"
          x2="320"
          y2="380"
          stroke="#88B772"
          strokeWidth="1.2"
          opacity="0.45"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.55;0.25"
            dur="3.4s"
            repeatCount="indefinite"
            begin="1.2s"
          />
        </line>
        <line
          x1="320"
          y1="380"
          x2="290"
          y2="410"
          stroke="#88B772"
          strokeWidth="1.3"
          opacity="0.5"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.6;0.3"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.6s"
          />
        </line>

        {/* Center - Corpus Callosum (Removed to keep text area clean) */}

        {/* Right Hemisphere - Frontal to Parietal */}
        <line
          x1="950"
          y1="180"
          x2="980"
          y2="200"
          stroke="#88B772"
          strokeWidth="1.3"
          opacity="0.5"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.6;0.3"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.2s"
          />
        </line>
        <line
          x1="980"
          y1="200"
          x2="1000"
          y2="230"
          stroke="#88B772"
          strokeWidth="1.2"
          opacity="0.45"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.55;0.25"
            dur="2.8s"
            repeatCount="indefinite"
            begin="0.7s"
          />
        </line>
        <line
          x1="920"
          y1="220"
          x2="900"
          y2="250"
          stroke="#88B772"
          strokeWidth="1.4"
          opacity="0.55"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.35;0.65;0.35"
            dur="3.1s"
            repeatCount="indefinite"
            begin="0.9s"
          />
        </line>
        <line
          x1="900"
          y1="250"
          x2="930"
          y2="280"
          stroke="#88B772"
          strokeWidth="1.1"
          opacity="0.4"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.2;0.5;0.2"
            dur="2.9s"
            repeatCount="indefinite"
            begin="0.3s"
          />
        </line>

        {/* Right Hemisphere - Frontal to Temporal */}
        <line
          x1="1000"
          y1="230"
          x2="1020"
          y2="320"
          stroke="#88B772"
          strokeWidth="1.0"
          opacity="0.35"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.15;0.45;0.15"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1.2s"
          />
        </line>
        <line
          x1="1020"
          y1="320"
          x2="1000"
          y2="350"
          stroke="#88B772"
          strokeWidth="1.3"
          opacity="0.5"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.6;0.3"
            dur="3.6s"
            repeatCount="indefinite"
            begin="0.8s"
          />
        </line>
        <line
          x1="1000"
          y1="350"
          x2="1040"
          y2="380"
          stroke="#88B772"
          strokeWidth="1.1"
          opacity="0.4"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.2;0.5;0.2"
            dur="3.3s"
            repeatCount="indefinite"
            begin="1.4s"
          />
        </line>

        {/* Right Hemisphere - Parietal to Occipital */}
        <line
          x1="930"
          y1="280"
          x2="880"
          y2="380"
          stroke="#88B772"
          strokeWidth="1.2"
          opacity="0.45"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.25;0.55;0.25"
            dur="3.4s"
            repeatCount="indefinite"
            begin="1.6s"
          />
        </line>
        <line
          x1="880"
          y1="380"
          x2="910"
          y2="410"
          stroke="#88B772"
          strokeWidth="1.3"
          opacity="0.5"
          className="connection-pulse"
        >
          <animate
            attributeName="opacity"
            values="0.3;0.6;0.3"
            dur="3.2s"
            repeatCount="indefinite"
            begin="0.8s"
          />
        </line>

        {/* Cross-hemisphere Connections - Removed to keep text area clean */}

        {/* Brainstem Connection (Removed to keep text area clean) */}
        {/* Brainstem connection (Removed to clean up bottom area) */}

        {/* Signal Bursts - Following realistic neural pathways */}
        <circle
          r="1.5"
          fill="url(#signalGradient)"
          opacity="0.8"
          className="signal-burst"
        >
          <animateMotion dur="4s" repeatCount="indefinite" begin="0s">
            <mpath href="#signalPath1" />
          </animateMotion>
          <animate
            attributeName="opacity"
            values="0;0.8;0"
            dur="4s"
            repeatCount="indefinite"
            begin="0s"
          />
        </circle>

        <circle
          r="1.2"
          fill="url(#signalGradient)"
          opacity="0.7"
          className="signal-burst"
        >
          <animateMotion dur="3.5s" repeatCount="indefinite" begin="1.5s">
            <mpath href="#signalPath2" />
          </animateMotion>
          <animate
            attributeName="opacity"
            values="0;0.7;0"
            dur="3.5s"
            repeatCount="indefinite"
            begin="1.5s"
          />
        </circle>

        {/* Signal burst 3 (Removed to clean up bottom area) */}

        {/* Signal Paths - Following anatomically accurate brain pathways */}
        <path
          id="signalPath1"
          d="M 250 180 L 220 200 L 200 230 L 180 320 L 200 350 L 160 380"
          fill="none"
        />
        <path
          id="signalPath2"
          d="M 950 180 L 980 200 L 1000 230 L 1020 320 L 1000 350 L 1040 380"
          fill="none"
        />
        {/* Signal path 3 (Removed to clean up bottom area) */}
      </svg>
    </div>
  );
}
